### ISSUE TITLE
Ender Dragon Breathe

### ISSUE THREAD

**Issue by EnderEXE2** [DragonMountsTeam/Dragon-Mounts-2#1]
Don't know if it's a bug. But why Ender Dragon Breathe gives the Wither II effect. It should work like the vanilla Ender Dragon Breathe.
Also here's the video.

https://github.com/user-attachments/assets/5ba4c495-b3e5-469f-be27-06c477aa8a39

**Comment by 2190303755** [comment]
Actually it spawned an Area Effect Cloud there. Comparing to Wither's, Ender's Area Effect Cloud has different particles, larger radius, longer duration. What's more, despite they sharing tha same type, effect from Ender has higher amplifier and longer duration.
It might be intended behavior.

**Comment by 2190303755** [comment]
Actually it spawned an Area Effect Cloud there. Comparing to Wither's, Ender's Area Effect Cloud has different particles, larger radius, longer duration. What's more, despite they sharing tha same type, effect from Ender has higher amplifier and longer duration.
It might be intended behavior.

**Comment by EnderEXE2** [comment]
> Actually it spawned an Area Effect Cloud there. Comparing to Wither's, Ender's Area Effect Cloud has different particles, larger radius, longer duration. What's more, despite they sharing tha same type, effect from Ender has higher amplifier and longer duration. It might be intended behavior.

Ah Ok.
