### ISSUE TITLE
Dragon Essence Issue

### ISSUE THREAD

**Issue by EnderEXE2** [DragonMountsTeam/Dragon-Mounts-2#10]
When tried to revive the dragon using Dragon Essence doensn't work.
https://youtu.be/E8SJ1pHvtF0?si=R5dpcQsYolf1uJfg

**Comment by Tomanex** [comment]
https://github.com/user-attachments/assets/0b9fe9cc-a0f5-45dc-babe-dd4f6402f5c8

**Comment by 2190303755** [comment]
It saved previous dragon's health so the new dragon was set dead when placed
XD

**Comment by EnderEXE2** [comment]
:(
