### ISSUE TITLE
Dragon Inventory 

### ISSUE THREAD

**Issue by EnderEXE2** [DragonMountsTeam/Dragon-Mounts-2#11]
So when an end crystal is there near a dragon and the inventory of dragon is opened, the trail of end crystal effect renders/shows out of the dragon inventory also. (Left, bottom only.

![image.png](https://github.com/user-attachments/assets/afeaa792-029c-48e4-847c-0e5602a5c015)

**Comment by Tomanex** [comment]
All dragons do this when near an end crystal?
