### ISSUE TITLE
Air breath texture

### ISSUE THREAD

**Issue by EnderEXE2** [DragonMountsTeam/Dragon-Mounts-2#15]
dont know if this is a bug, but air breath renders in the game like this
![Screenshot (10)](https://github.com/user-attachments/assets/818968e9-d367-4e8a-b3b3-03f14cebfd43)

**Comment by EnderEXE2** [comment]
a bit dim/ black effect.
appears only in air breath . Other breath doesnt have this. Perhaps a texture related thing.

**Comment by Tomanex** [comment]
Yeah it can't be changed sadly, a texture with no colors usually does this.

**Comment by Tomanex** [comment]
Actually, keep it. I think Air can also mean Smoke. And it's fitting.

**Comment by Tomanex** [comment]
Does this fix the issue, number-man?
![breath_air](https://github.com/user-attachments/assets/dad2dfb6-f479-47c3-86b6-692b2efa4a14)

**Comment by 2190303755** [comment]
That's related to the `lightingState` in `GlStateManager`. Actually all types of breath was influenced by it, but lighter color is more noticeable.

**Comment by Tomanex** [comment]
Ah I see
