### ISSUE TITLE
Credits.txt and Splash.txt

### ISSUE THREAD

**Issue by Tomanex** [DragonMountsTeam/Dragon-Mounts-2#17]
Adding a credits text in the files to credit everyone maintaining the old and current development of DM2.

Splash texts returning from DM1, with new ones referencing other Dragon Mounts projects. ; )
[splashes.txt](https://github.com/user-attachments/files/17647518/splashes.txt)

**Comment by Tomanex** [comment]
Updated Splash.txt
[splashes.txt](https://github.com/user-attachments/files/17647709/splashes.txt)

**Comment by 2190303755** [comment]
That's not a good idea especially when every mod append its credit to splash.
It can be added to mod's description or repo's README.md

**Comment by Tomanex** [comment]
Ah ok
