### ISSUE TITLE
Dragon Amulet Textures

### ISSUE THREAD

**Issue by JDSK0ala** [DragonMountsTeam/Dragon-Mounts-2#18]
The texture for the Water and Fire Dragon Amulets do not appear as intended
Version tested: DragonMounts2-2.0.0-24w45a

![image](https://github.com/user-attachments/assets/b4edf876-f162-48bc-b956-d9c218f5ed05)
![image](https://github.com/user-attachments/assets/22dedf97-7fd1-434f-82cf-60b175eb31a0)

**Comment by 2190303755** [comment]
I hate the aliases for ender and water

**Comment by JDSK0ala** [comment]
Lol. I am still testing some of the dragons. It appears that some missing textures are gender specific. I just tested the Terra Dragon and if the dragon is Female, the texture is missing but if it is male, the texture is normal

**Comment by JDSK0ala** [comment]
Right, here is a list of all the amulets with bugged textures that I am currently aware of:
1. Male Water
2. Female Water
3. Female Nether
4. Female Terra
5. Female Fire
6. Female Sunlight
7. Male Moonlight
8. Female Storm

**Comment by 2190303755** [comment]
a reason may be the '2' suffix in their breed
