### ISSUE TITLE
New Wand Textures

### ISSUE THREAD

**Issue by Tomanex** [DragonMountsTeam/Dragon-Mounts-2#19]
I know the item is useless but any ideas on what we can do with it?
[Dragon Wand.zip](https://github.com/user-attachments/files/17661314/Dragon.Wand.zip)

**Comment by Tomanex** [comment]
HD
![Untitled488_20241107200740](https://github.com/user-attachments/assets/b4555dc4-b356-48a8-9c96-83276b95b58a)

**Comment by 2190303755** [comment]
added in 267b8e2d75a4897177b9d8925ab4dc252bb40403
