### ISSUE TITLE
Hatchling dragons are able to breathe fire

### ISSUE THREAD

**Issue by EnderEXE2** [DragonMountsTeam/Dragon-Mounts-2#2]
Fire breath doesnt often set blocks on fire. And Hatchlings are still able to breath fire when mount on shoulders.

https://github.com/user-attachments/assets/1de331de-dbc3-4e5c-a3cf-046dca8a4df7

**Comment by 2190303755** [comment]
Do **NOT** submit irrelevant problems on single issue

**Comment by EnderEXE2** [comment]
> Do **NOT** submit irrelevant problems on single issue
Sorry.

**Comment by 2190303755** [comment]
Fixed in f76c165994f3455ece2c5e8ffd75c65973726279.
Lava cannot set blocks on fire immediately either, so it makes sense to ignite blocks by chance.

**Comment by EnderEXE2** [comment]
> Fixed in f76c165994f3455ece2c5e8ffd75c65973726279.
> Lava cannot set blocks on fire immediately either, so it makes sense to ignite blocks by chance.
 Nvm
