### ISSUE TITLE
Dragon Breath Sound

### ISSUE THREAD

**Issue by EnderEXE2** [DragonMountsTeam/Dragon-Mounts-2#20]
Dragon Breath Sound isn't producing when a Dragon is breathing .

**Comment by 2190303755** [comment]
Did it work in previous version?

**Comment by EnderEXE2** [comment]
I don't remember exactly. But it happened when the New breath textures appeared.

**Comment by 2190303755** [comment]
do not involve unrelated changes

**Comment by 2190303755** [comment]
that works in 1.6.4
