### ISSUE TITLE
Dragon's name cannot be serialized properly & Anvil should change dragon's name by renaming amulet

### ISSUE THREAD

**Issue by EnderEXE2** [DragonMountsTeam/Dragon-Mounts-2#4]
You can name the dragon without needing a Name Tag by renaming the Dragon Amulet with a dragon inside in an Anvil. But after renaming the Dragon Amulet and putting the Dragon back out, the name of the Dragon and the Dragon Amulet gets removed.

**Comment by 2190303755** [comment]
What do you mean by "**can** name the dragon ... by renaming the Dragon Amulet"

**Comment by 2190303755** [comment]
Fixed in f76c165994f3455ece2c5e8ffd75c65973726279.
There is no sign that the amulet can change dragon's name by anvil.

**Comment by EnderEXE2** [comment]
> Fixed in f76c165994f3455ece2c5e8ffd75c65973726279.
> There is no sign that the amulet can change dragon's name by anvil.

It can if Dragon is inside it .  In the latest video of RPG which is deleted now It was shown that if a dragon is inside the Amulet and we rename it dragon  gets a name tag without even requiring Name Tag .
