### ISSUE TITLE
Amulet Teleportation Bug

### ISSUE THREAD

**Issue by EnderEXE2** [DragonMountsTeam/Dragon-Mounts-2#6]
So basically, trying to pick up a dragon with a amulet teleports us to the dragon's [position.]()

https://github.com/user-attachments/assets/77884082-27e1-4a59-9a3c-b017010a5bbf

**Comment by 2190303755** [comment]
can not confirm

**Comment by Tomanex** [comment]
I think he means whenever you pick up the dragon, it thinks you want to mount the dragon.

**Comment by 2190303755** [comment]
It should not be considered as a bug before it could be reproduced

**Comment by Tomanex** [comment]
Alright
